//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace vsa.mobnavsales.android.PDA_General_Web_Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PDA_General_Web_Service_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/PDA_General_Web_Service")]
    public partial class PDA_General_Web_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback G_wsfnGetSalesUoMOperationCompleted;
        
        private System.Threading.SendOrPostCallback G_wsfnGetSalesUnitPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback G_wsfnGetPDARoleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PDA_General_Web_Service() {
            this.Url = "http://mscrm.aecomputer.com:7147/DynamicsNAV70/WS/ReplaceWithAPercentEncodedCompa" +
                "nyName/Codeunit/PDA_General_Web_Service";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event G_wsfnGetSalesUoMCompletedEventHandler G_wsfnGetSalesUoMCompleted;
        
        /// <remarks/>
        public event G_wsfnGetSalesUnitPriceCompletedEventHandler G_wsfnGetSalesUnitPriceCompleted;
        
        /// <remarks/>
        public event G_wsfnGetPDARoleCompletedEventHandler G_wsfnGetPDARoleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PDA_General_Web_Service:G_wsfnGetSalesUoM" +
            "", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PDA_General_Web_Service", ResponseElementName="G_wsfnGetSalesUoM_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PDA_General_Web_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string G_wsfnGetSalesUoM(int poptDocType, string pcdDocNo, string pcdSellTo, int pintDocDay, int pintDocMonth, int pintDocYear, string pcdItemNo) {
            object[] results = this.Invoke("G_wsfnGetSalesUoM", new object[] {
                        poptDocType,
                        pcdDocNo,
                        pcdSellTo,
                        pintDocDay,
                        pintDocMonth,
                        pintDocYear,
                        pcdItemNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void G_wsfnGetSalesUoMAsync(int poptDocType, string pcdDocNo, string pcdSellTo, int pintDocDay, int pintDocMonth, int pintDocYear, string pcdItemNo) {
            this.G_wsfnGetSalesUoMAsync(poptDocType, pcdDocNo, pcdSellTo, pintDocDay, pintDocMonth, pintDocYear, pcdItemNo, null);
        }
        
        /// <remarks/>
        public void G_wsfnGetSalesUoMAsync(int poptDocType, string pcdDocNo, string pcdSellTo, int pintDocDay, int pintDocMonth, int pintDocYear, string pcdItemNo, object userState) {
            if ((this.G_wsfnGetSalesUoMOperationCompleted == null)) {
                this.G_wsfnGetSalesUoMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnG_wsfnGetSalesUoMOperationCompleted);
            }
            this.InvokeAsync("G_wsfnGetSalesUoM", new object[] {
                        poptDocType,
                        pcdDocNo,
                        pcdSellTo,
                        pintDocDay,
                        pintDocMonth,
                        pintDocYear,
                        pcdItemNo}, this.G_wsfnGetSalesUoMOperationCompleted, userState);
        }
        
        private void OnG_wsfnGetSalesUoMOperationCompleted(object arg) {
            if ((this.G_wsfnGetSalesUoMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.G_wsfnGetSalesUoMCompleted(this, new G_wsfnGetSalesUoMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PDA_General_Web_Service:G_wsfnGetSalesUni" +
            "tPrice", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PDA_General_Web_Service", ResponseElementName="G_wsfnGetSalesUnitPrice_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PDA_General_Web_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public decimal G_wsfnGetSalesUnitPrice(int poptDocType, string pcdDocNo, string pcdSellTo, int pintDocDay, int pintDocMonth, int pintDocYear, string pcdItemNo, decimal pdecQuantity, string pcdUoM) {
            object[] results = this.Invoke("G_wsfnGetSalesUnitPrice", new object[] {
                        poptDocType,
                        pcdDocNo,
                        pcdSellTo,
                        pintDocDay,
                        pintDocMonth,
                        pintDocYear,
                        pcdItemNo,
                        pdecQuantity,
                        pcdUoM});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void G_wsfnGetSalesUnitPriceAsync(int poptDocType, string pcdDocNo, string pcdSellTo, int pintDocDay, int pintDocMonth, int pintDocYear, string pcdItemNo, decimal pdecQuantity, string pcdUoM) {
            this.G_wsfnGetSalesUnitPriceAsync(poptDocType, pcdDocNo, pcdSellTo, pintDocDay, pintDocMonth, pintDocYear, pcdItemNo, pdecQuantity, pcdUoM, null);
        }
        
        /// <remarks/>
        public void G_wsfnGetSalesUnitPriceAsync(int poptDocType, string pcdDocNo, string pcdSellTo, int pintDocDay, int pintDocMonth, int pintDocYear, string pcdItemNo, decimal pdecQuantity, string pcdUoM, object userState) {
            if ((this.G_wsfnGetSalesUnitPriceOperationCompleted == null)) {
                this.G_wsfnGetSalesUnitPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnG_wsfnGetSalesUnitPriceOperationCompleted);
            }
            this.InvokeAsync("G_wsfnGetSalesUnitPrice", new object[] {
                        poptDocType,
                        pcdDocNo,
                        pcdSellTo,
                        pintDocDay,
                        pintDocMonth,
                        pintDocYear,
                        pcdItemNo,
                        pdecQuantity,
                        pcdUoM}, this.G_wsfnGetSalesUnitPriceOperationCompleted, userState);
        }
        
        private void OnG_wsfnGetSalesUnitPriceOperationCompleted(object arg) {
            if ((this.G_wsfnGetSalesUnitPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.G_wsfnGetSalesUnitPriceCompleted(this, new G_wsfnGetSalesUnitPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PDA_General_Web_Service:G_wsfnGetPDARole", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PDA_General_Web_Service", ResponseElementName="G_wsfnGetPDARole_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PDA_General_Web_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool G_wsfnGetPDARole(string pcdUserName) {
            object[] results = this.Invoke("G_wsfnGetPDARole", new object[] {
                        pcdUserName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void G_wsfnGetPDARoleAsync(string pcdUserName) {
            this.G_wsfnGetPDARoleAsync(pcdUserName, null);
        }
        
        /// <remarks/>
        public void G_wsfnGetPDARoleAsync(string pcdUserName, object userState) {
            if ((this.G_wsfnGetPDARoleOperationCompleted == null)) {
                this.G_wsfnGetPDARoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnG_wsfnGetPDARoleOperationCompleted);
            }
            this.InvokeAsync("G_wsfnGetPDARole", new object[] {
                        pcdUserName}, this.G_wsfnGetPDARoleOperationCompleted, userState);
        }
        
        private void OnG_wsfnGetPDARoleOperationCompleted(object arg) {
            if ((this.G_wsfnGetPDARoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.G_wsfnGetPDARoleCompleted(this, new G_wsfnGetPDARoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void G_wsfnGetSalesUoMCompletedEventHandler(object sender, G_wsfnGetSalesUoMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class G_wsfnGetSalesUoMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal G_wsfnGetSalesUoMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void G_wsfnGetSalesUnitPriceCompletedEventHandler(object sender, G_wsfnGetSalesUnitPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class G_wsfnGetSalesUnitPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal G_wsfnGetSalesUnitPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void G_wsfnGetPDARoleCompletedEventHandler(object sender, G_wsfnGetPDARoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class G_wsfnGetPDARoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal G_wsfnGetPDARoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591